### ISSUE TITLE
Using the MediaWiki OAuth2 extension with Slack as the identity provider

### ISSUE THREAD

**Issue by dtenenba** [adam-paterson/oauth2-slack#12]
Hi,

I am sorry to bug you with this question that is not directly related to your code, but I am hoping you can help me. I'm trying to use the [MediaWiki OAuth2 extension](https://github.com/Schine/MW-OAuth2Client) which is based on the [oauth2-client](https://github.com/thephpleague/oauth2-client) that you have written this provider for. Unfortunately the documentation of the MediaWiki extension is somewhat inadequate and it seems to be impossible to contact the developers (issues are not enabled on their repository and one email address I managed to find for them bounced). I'm hoping you can help with what should be a quick question, or direct me to a 

Their documentation says to put the following in my `LocalSettings.php` but does not explain adequately what the values should be. This is what I have set them to so far (credentials & my domain name are obfuscated):

```php
$wgOAuth2Client['client']['id']     = ''; // The client ID assigned to you by the provider
$wgOAuth2Client['client']['secret'] = ''; // The client secret assigned to you by the provider

$wgOAuth2Client['configuration']['authorize_endpoint']     = ''; // Authorization URL
$wgOAuth2Client['configuration']['access_token_endpoint']  = ''; // Token URL
$wgOAuth2Client['configuration']['api_endpoint']           = ''; // URL to fetch user JSON
$wgOAuth2Client['configuration']['redirect_uri']           = ''; // URL for OAuth2 server to redirect to

$wgOAuth2Client['configuration']['username'] = 'username'; // JSON path to username
$wgOAuth2Client['configuration']['email'] = 'email'; // JSON path to email
```

I’m not sure whether I did this correctly or what the remaining blank fields should be set to. Is there an example I can follow?

So now, I have an “OAuth2 login”  link on my Wiki (next to the Login) link which goes to 

`https://wiki.mydomain.com/mediawiki/index.php?title=Special:OAuth2Client/redirect&returnto=Main+Page`

That seems kind of wrong? Anyway, I click it and nothing happens. If I go directly to 

`https://slack.com/oauth/authorize?scope=identity.basic&client_id=xxx.yyy`

it redirects me to 

`https://wiki.mydomain.com/mediawiki/index.php/Special:OAuth2Client/redirect?code=aaa.bbb.2a30b3c73c&state=`

but does not log me in.

What am I doing wrong?

Also, further questions:

I want authentication ONLY to be done with OAuth2 and Slack. How do I disable/replace the default Login functionality?

Once I have done this, how do I tell whether a user is an admin or not? 

I’d like to have to way to define particular users as admins. It doesn’t matter how this is done, really, as long as I can do it somehow.

**Comment by adam-paterson** [comment]
@dtenenba I'll have to setup a MediaWiki project locally and test later to see if I can replicate and fix the issues you're having. Until then, I have updated the configuration with the values returned by `AdamPaterson\OAuth2\Client\Provider\Slack`.

```php

wfLoadExtension( 'MW-OAuth2Client' );

$wgOAuth2Client['client']['id']     = 'SLACK-CLIENT-ID'; // The client ID assigned to you by the provider
$wgOAuth2Client['client']['secret'] = 'SLACK-SECRET'; // The client secret assigned to you by the provider

$wgOAuth2Client['configuration']['authorize_endpoint']     = 'https://slack.com/oauth/authorize'; // Authorization URL
$wgOAuth2Client['configuration']['access_token_endpoint']  = 'https://slack.com/api/oauth.access'; // Token URL
$wgOAuth2Client['configuration']['api_endpoint']           = 'https://slack.com/api/users.info'; // URL to fetch user JSON
$wgOAuth2Client['configuration']['redirect_uri']           = 'http://your.wiki.domain/path/to/wiki/Special:OAuth2Client/callback'; // URL for OAuth2 server to redirect to

$wgOAuth2Client['configuration']['username'] = 'username'; // JSON path to username
$wgOAuth2Client['configuration']['email'] = 'email'; // JSON path to email
```

**Comment by dtenenba** [comment]
Thank you for the suggested configuration. I'm not sure you should spend time installing MediaWiki. It seems like they are not supporting the OAuth2 Client extension. I may try and use yours instead. If I run into problems I will file a separate issue. Thanks.

**Comment by adam-paterson** [comment]
@dtenenba Okay, I'll hold off for now. Definitely get in touch if you find an issue with this library though.
