### ISSUE TITLE
Build query with http_build_query

### ISSUE THREAD

**Issue by shadowhand** [adam-paterson/oauth2-slack#2]
Using [`sprintf` to build a query](https://github.com/adam-paterson/oauth2-slack/blob/2710b26af0f70b934d258372244e63c3c9897ef9/src/Provider/Slack.php#L52-L54) is unsafe and could lead to incorrect encoding. Using [`http_build_query`](http://php.net/http_build_query) is the most correct way to create query strings.

**Comment by adam-paterson** [comment]
Fixed in #3.

**Comment by adam-paterson** [comment]
@shadowhand Thanks
