### ISSUE TITLE
Use updated endpoint for user identity info

### ISSUE THREAD

**Issue by AndreiIgna** [adam-paterson/oauth2-slack#21]
When the OAuth is used for "Sign In with Slack", the Slack API provides a separate endpoint for user info, `https://slack.com/api/users.identity` instead of `https://slack.com/api/users.identity`

This is important for login-only apps, as the apps that use only `identity.*` scopes are not counted as app integrations. Lots of teams prefer this so the app integration limit is left unchanged.

There's more info here https://api.slack.com/docs/sign-in-with-slack#using_tokens_to_retrieve_user_and_team_information and have a few suggestions:
- make the [endpoint for user details](https://github.com/adam-paterson/oauth2-slack/blob/develop/src/Provider/Slack.php#L58) editable. If custom endpoint is not provided, use default one
- detect if scopes are `identity.*` then use `https://slack.com/api/users.identity`. If not using `identity.*` scopes, use default

**Comment by adam-paterson** [comment]
@AndreiIgna I've got no idea how I wasn't notified of this one. I'll look into it this week and get a release out.

Thanks for your interest in the library.

**Comment by AndreiIgna** [comment]
hey @adam-paterson thanks for checking this. I've used the Slack API in more projects now and this change would be definitely helpful. 

For "Sign in with Slack" only apps, would be helpful to change the user info endpoint. 

Also saw something else which can be improved:
- adding the auth headers used by this Slack https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L804 making it easier to make API requests after sign in
- `user:read` scope used in Readme.md is not valid. The correct one would be `users:read`, which actually gives access to all users in Slack team. Single user info may have been available previously, but Slack changes their API too quickly for these things..
<img width="494" alt="screen shot 2018-06-21 at 12 57 09" src="https://user-images.githubusercontent.com/263021/41771011-190dbf96-7614-11e8-9e2f-5fe5b6519ebc.png">

Can make a PR for these as well
