### ISSUE TITLE
Where is state supposed to come from?

### ISSUE THREAD

**Issue by unformatt** [adam-paterson/oauth2-slack#5]
I've set my app's Redirect URI to a PHP script which uses the example code you provided in the README.

Slack is not sending state to my URL. It's just sending this:

`?code=2916289853.27927757863.a3a02b156e&state=`

So I get `Invalid state` error.

So I set state in the URL, manually, just to see if I can get past that error. Same error. Then I see state is compared against a session variable that is set in this code:

```
$_SESSION['oauth2state'] = $provider->getState();
```

This code is never reached because Slack never hits my Requst URL without the code in the URL. Am I doing it wrong?

**Comment by cwhite92** [comment]
The state parameter is set by you. It's an optional parameter that allows you to check that the person completing the OAuth flow is the same person that started it. It's meant to work like so:

1) User loads your page. You generate a unique, random string.
2) The link on your page that redirects to Slack's OAuth flow should have `?state=YourRandomString` as a query parameter.
3) When Slack OAuth flow completes and sends the user back to your site, Slack will also send the `&state=YourRandomString` query parameter back (which is what you're seeing)
4) You're meant to check that string against the one generated in step 1, to confirm that a third party has not gone through the OAuth flow.

**Comment by adam-paterson** [comment]
Sorry @unformatt it's taken so long to respond, I didn't receive a notification for the issue.

@cwhite92 answer is correct. When you create your `\AdamPaterson\OAuth2\Client\Provider\Slack` instance you should pass it a state.

```php
<?php
$provider = new \AdamPaterson\OAuth2\Client\Provider\Slack([
    'clientId'          => '{slack-client-id}',
    'clientSecret'      => '{slack-client-secret}',
    'redirectUri'       => 'https://example.com/callback-url',
    'state'    =>     uniqid()
]);

if (!isset($_GET['code'])) {

    // If we don't have an authorization code then get one
    $authUrl = $provider->getAuthorizationUrl();
    $_SESSION['oauth2state'] = $provider->getState();
    header('Location: '.$authUrl);
    exit;

// Check given state against previously stored one to mitigate CSRF attack
} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

    unset($_SESSION['oauth2state']);
    exit('Invalid state');

} else {

    // Try to get an access token (using the authorization code grant)
    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code']
    ]);```
