### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by adam-paterson** [adam-paterson/oauth2-slack#6]

**Comment by jmauerhan** [comment]
Can you be more specific? Are you just wanting to upgrade everything to newer versions and confirm it all still works?

**Comment by adam-paterson** [comment]
Sorry, this was a shameless attempt to get myself up to the Hacktoberfest quota. However I really don't have the time.

I'd like to update as much as possible. Most of which would be handled by the version constraint on `thephpleague/oauth2-client` package.

**Comment by jmauerhan** [comment]
Cool - I'll be happy to take a look if you want help with it?

**Comment by adam-paterson** [comment]
@jmauerhan feel free!

**Comment by jmauerhan** [comment]
Other than missing your composer.lock, the only thing that is seriously out of date is actually PHPUnit. league/oauth2-client on 1.4.2 passed your existing tests for me. I'll submit a PR with the lock file, as well as an update to newer PHPUnit.

**Comment by jmauerhan** [comment]
Do you want to continue to support PHP 5.5, or move up to >=5.6 since 5.5 is no longer supported by PHP? (Ref: http://php.net/supported-versions.php)

**Comment by adam-paterson** [comment]
>=5.6 please. Don't forget to drop 5.5 from the Travis config otherwise PHPUnit will fail the build.

**Comment by adam-paterson** [comment]
@jmauerhan Resolved by #11
